name: CI iOS

on:
  push:
    branches: [ main ]
    paths:
      - 'ios/**'
      - 'package.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'ios/**'
      - 'package.json'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: c-hive/gha-npm-cache@v1

      - name: Install tools
        run: brew install xcbeautify

      - name: Install dependencies
        run: npm install

      - name: Install iOS Dependency
        run: npm run install:ios

      - name: Run iOS debug build
        run: npm run build:ios:debug

      - name: Run iOS release build
        run: npm run build:ios:release
